services:
  - type: web
    name: miapp
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate && gunicorn miapp.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: miapp-db
          property: connectionString

databases:
  - name: miapp-db
    plan: free
